### ISSUE TITLE
Variable name inputName='tracePlot1' not working

### ISSUE THREAD

**Issue by SpehleHSGM** [mw201608/Shiny#1]
jsCode2 <- "shinyjs.plotlyGetTraces =  function(id,inputName='tracePlot1'){
        var out = [];
        for(var i = 0; i < document.getElementById(id).data.length; i++) {
            out.push('trace ' + i);
        }
        Shiny.setInputValue('tracesPlot1', out);
    }"

Isn't working for me. 

Using static name `Shiny.setInputValue('tracesPlot1', out);` fixed the problem on ubuntu system R version 4.2.1 (2022-06-23), shiny 1.7.4, shinyjs 2.1.0, htmlwidgets 1.6.1 and plotly 4.10.1

**Comment by mw201608** [comment]
I don't see any issue on Ubuntu 22.04, R version 4.2.1, shiny 1.7.4, shinyjs 2.1.0, htmlwidgets 1.6.1 and plotly 4.10.1.
